pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                echo 'Test Jenkinsfile - web-1/dev job is working on the test-branch-parameter branch'
            }
        }
    }
}
